version = 1

[[annotations]]
path = [
    ".github/workflows/*",
    ".gitignore",
    ".golangci.yml",
    "go.mod",
    "go.sum",
    "Makefile",
    "README.md"
]
precedence = "override"
SPDX-FileCopyrightText = "Public domain"
SPDX-License-Identifier = "CC0-1.0"
